#!/bin/bash

# Give execute permissions to all files in current directory and subdirectories
chmod +x *
chmod -R +x */

# Add, commit and push changes to GitHub
git add .
git commit -m "Permissions $(git rev-list --count HEAD)"
git push origin main
