#!/bin/bash

# Task 0: Create and run the 0-alias script
echo -e '#!/bin/bash\nalias ls="rm *"' > 0-alias
chmod +x 0-alias
./0-alias
git add .
git commit -m "Colile"
git push

# Task 1: Create and run the 1-hello_you script
echo -e '#!/bin/bash\necho "hello $USER"' > 1-hello_you
chmod +x 1-hello_you
./1-hello_you
git add .
git commit -m "Colile"
git push

# Task 2: Create and run the 2-path script
echo -e '#!/bin/bash\nexport PATH=$PATH:/action' > 2-path
chmod +x 2-path
./2-path
git add .
git commit -m "Colile"
git push

# Task 3: Create and run the 3-paths script
echo -e '#!/bin/bash\necho $((`echo $PATH | grep -o ":/" | wc -l`+ 1))' > 3-paths
chmod +x 3-paths
./3-paths
git add .
git commit -m "Colile"
git push

# Task 4: Create and run the 4-global_variables script
echo -e '#!/bin/bash\nprintenv' > 4-global_variables
chmod +x 4-global_variables
./4-global_variables
git add .
git commit -m "Colile"
git push

# Task 5: Create and run the 5-local_variables script
echo -e '#!/bin/bash\nset' > 5-local_variables
chmod +x 5-local_variables
./5-local_variables
git add .
git commit -m "Colile"
git push

# Task 6: Create and run the 6-create_local_variable script
echo -e '#!/bin/bash\nBEST="School"' > 6-create_local_variable
chmod +x 6-create_local_variable
./6-create_local_variable
git add .
git commit -m "Colile"
git push

# Task 7: Create and run the 7-create_global_variable script
echo -e '#!/bin/bash\nexport BEST=School' > 7-create_global_variable
chmod +x 7-create_global_variable
./7-create_global_variable
git add .
git commit -m "Colile"
git push

# Task 8: Create and run the 8-true_knowledge script
echo -e '#!/bin/bash\necho $(($TRUEKNOWLEDGE + 128))' > 8-true_knowledge
chmod +x 8-true_knowledge
./8-true_knowledge
git add .
git commit -m "Colile"
git push

# Task 9: Create and run the 9-divide_and_rule script
echo -e '#!/bin/bash\necho $(($POWER / $DIVIDE))' > 9-divide_and_rule
chmod +x 9-divide_and_rule
./9-divide_and_rule
git add .
git commit -m "Colile"
git push

# Task 10: Create and run the 10-love_exponent_breath script
echo -e '#!/bin/bash\necho "$((BREATH**$LOVE))"' > 10-love_exponent_breath
chmod +x 10-love_exponent_breath
./10-love_exponent_breath
git add .
git commit -m "Colile"
git push

# Task 11: Create and run the 11-binary_to_decimal script
echo -e '#!/bin/bash\necho "$((2#$BINARY))"' > 11-binary_to_decimal
chmod +x 11-binary_to_decimal
./11-binary_to_decimal
git add .
git commit -m "Colile"
git push

# Task 12: Create and run the 12-combinations script
echo -e '#!/bin/bash\necho {a..z}{a..z} | tr " " "\n" | grep -v "oo"' > 12-combinations
chmod +x 12-combinations
./12-combinations
git add .
git commit -m "Colile"
git push

# Task 13: Create and run the 13-print_float script
echo -e "#!/bin/bash\nprintf \"%.2f\" \$NUM | sort" > 13-print_float
chmod +x 13-print_float
./13-print_float
git add .
git commit -m "Colile"
git push

# Task 100: Create and run the 100-decimal_to_hexadecimal script
echo -e "#!/bin/bash\nprintf '%x\n' \$DECIMAL" > 100-decimal_to_hexadecimal
chmod +x 100-decimal_to_hexadecimal
./100-decimal_to_hexadecimal
git add .
git commit -m "Colile"
git push

# Task 101: Create and run the 101-rot13 script
echo -e "#!/bin/bash\ntr 'A-Za-z' 'N-ZA-Mn-za-m'" > 101-rot13
chmod +x 101-rot13
./101-rot13
git add .
git commit -m "Colile"
git push

# Task 102: Create and run the 102-odd script
echo -e "#!/bin/bash\nperl -lne 'print if \$. % 2 ==1'" > 102-odd
chmod +x 102-odd
./102-odd
git add .
git commit -m "Colile"
git push

# Task 103: Create and run the 103-water_and_stir script
echo -e "#!/bin/bash\necho \$(printf %o \$((\$((5#\\\$(echo \$WATER | tr 'water' '01234'))) + \$((5#\\\$(echo \$STIR | tr 'stir.' '01234'))))) | tr '01234567' 'bestchol')" > 103-water_and_stir
chmod +x 103-water_and_stir
./103-water_and_stir
git add .
git commit -m "Colile"
git push
