#!/usr/bin/env bash
# Install and configure Nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'
sudo service nginx restart
