#!/usr/bin/env bash
# Installs Nginx that listens on port 80

echo -e "Updating and installing Nginx.\n"

sudo apt-get -y update
sudo apt-get -y install nginx

echo -e "\nSetting up some minor stuff.\n"

sudo service nginx start
sudo ufw allow 'Nginx HTTP'

# Giving user ownership to site
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
echo -e "\nNginx has been configured to redirect /redirect_me to "
echo -e "https://www.youtube.com/watch?v=QH2-TGUlwu4 with a 301 Moved Permanently status.\n"