#!/usr/bin/env bash
# Configure Nginx to redirect /redirect_me to another page

if ! dpkg -l | grep -q nginx; then
    apt-get -y update
    apt-get -y install nginx
fi

echo '
location /redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}
' > /etc/nginx/sites-available/default

service nginx restart
