#!/usr/bin/env bash
# Installs Nginx that listens on port 80

sudo apt-get -y update
sudo apt-get -y install nginx

sudo service nginx start
sudo ufw allow 'Nginx HTTP'

# Giving user ownership to site
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
