#!/usr/bin/env bash
# Configure Nginx to serve a custom 404 page

if ! dpkg -l | grep -q nginx; then
    apt-get -y update
    apt-get -y install nginx
fi

echo 'Ceci n'\''est pas une page' > /var/www/html/404.html

sed -i 's|error_page 404 /404.html;|error_page 404 /404.html;\n    location /404.html {\n        root /var/www/html;\n    }|g' /etc/nginx/sites-available/default

sed -i 's|try_files \$uri \$uri/ =404;|try_files \$uri \$uri/ =404 /404.html;|g' /etc/nginx/sites-available/default

service nginx restart
