#!/usr/bin/env bash
# This script ensures Nginx is running and listening on port 80 in 5 lines or less.
sudo service nginx stop
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
