#!/usr/bin/env bash
# This script fixes Nginx configuration to ensure it listens on port 80 in 5 lines or less.
sudo service nginx stop
sudo rm -f /etc/nginx/sites-enabled/default
sudo service nginx start
