#!/usr/bin/env bash
# Print a list of currently running processes
# Show all processes for all users, including those without a TTY
# Display in a user-oriented format with process hierarchy

ps -ef --forest
