#!/usr/bin/env bash
# prints numbers from 1 to 20 and:
# prints 4 and then bad luck from China for the 4th loop iteration
# prints 9 and then bad luck from Japan for the 9th loop iteration
# prints 17 and then bad luck from Italy for the 17th loop iteration
count=1
while [ $count -le 20 ]
do
	case $count in
		4)
			echo -e "4\nbad luck from China"
			;;
		9)
			echo -e "9\nbad luck from Japan"
			;;
		17)
			echo -e "17\nbad luck from Italy"
			;;
		*)
			echo $count
	esac
	count=$((count + 1))
done
