#!/usr/bin/env bash
# prints the content of the current directory
# Where only the part of the name after the first dash is displayed

for file in *; do
  if [[ ! -d $file && $file != .* ]]; then
    name=${file#*-}
    echo $name
  fi
done
