#!/usr/bin/env bash
# 7 lines or less: run nginx as nginx user on 8080
sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80 default_server;/8080 default_server;/g' /etc/nginx/sites-available/default
service nginx restart
