#!/usr/bin/env bash
# Run nginx as nginx user on 8080 in 7 lines or less
id nginx 2>/dev/null || useradd -r -s /usr/sbin/nologin nginx
grep -q '^user nginx' /etc/nginx/nginx.conf || sed -i '1iuser nginx' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server/listen 8080 default_server/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server/listen [::]:8080 default_server/' /etc/nginx/sites-available/default
nginx -t
service nginx restart
