#!/bin/bash

ssh-keygen -t rsa -b 4096 -f school -N betty

echo "Generating public/private rsa key pair."
echo "Your identification has been saved in school." 
echo "Your public key has been saved in school.pub."
echo "The key fingerprint is:"
ssh-keygen -l -f school
echo "The key's randomart image is:" 
ssh-keygen -lf school
